### ISSUE TITLE
Funcionalidades complementares

### ISSUE THREAD

**Issue by rafatosta** [JvCedrazC/Library_Management#3]
Não identifiquei a implementação e testes das seguintes funcionalidades:

- Empréstimo e Devolução
- Reserva de Livros
- Renovação de Empréstimos
- Relatórios e Estatísticas
- Registro de Multas

**Comment by JvCedrazC** [comment]
Implementando os testes das funcionalidades: Empréstimo e Devolução, Reserva de Livros, Renovação de Empréstimos e Registro de Multas.
Criando a funcionalidade: Relatórios e Estatísticas
