### ISSUE TITLE
Commits não estruturados adequadamente

### ISSUE THREAD

**Issue by rafatosta** [JvCedrazC/Library_Management#5]

**Comment by JvCedrazC** [comment]
Professor, bom dia, dúvida sobre os commits: estou usando como referência aquele repositório do senhor. por favor quais são os erros?

**Comment by rafatosta** [comment]
> Professor, bom dia, dúvida sobre os commits: estou usando como referência aquele repositório do senhor. por favor quais são os erros?

Há vários commits que não descrevem brevemente o que foi alterado.
O que estão sendo atualizados nesses arquivos? É uma correção, nova funcionalidade?
![image](https://github.com/JvCedrazC/Library_Management/assets/18619894/c15b884b-ea36-4e98-8c33-5aba21c9992c)

Descrições vagas. Novo atributo de onde?  É preciso abrir o commit para saber do que se trata.
![image](https://github.com/JvCedrazC/Library_Management/assets/18619894/3211791c-084a-4766-bc12-3a3f4f816e38)

Nota que você colocou descrições vagas em todo o desenvolvimento.
![image](https://github.com/JvCedrazC/Library_Management/assets/18619894/7f851970-588f-4be5-84fb-1abce587fe10)

 A padronização dos commits não consiste apenas em colocar um icone ou tag, mas a forma de descrever o que foi alterado em cada commit. 
Olha a motivação para padronizar os commits
![image](https://github.com/JvCedrazC/Library_Management/assets/18619894/b0c7b843-4c48-48a9-85b8-60f008ff9314)

Por favor, faça uma leitura 
https://github.com/rafatosta/padroes-de-commits
